apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: acghfxw8g-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: acghfxw8g-python 
  name: acghfxw8g-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: acghfxw8g-python 
